databases:
  - name: ambrosia_burgers-db
    databaseName: amobrosia_burgers
    user: hfalkenrath

services:
  - type: web
    name: ambrosia_burgers-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ambrosia_burgers-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false